[package]
name = "advisory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.47.0"
aws-sdk-neptune = "0.17.0"
axum = "0.5.15"
tokio = { version = "1.20.1", features = ["full"] }
