services:
  database:
    container_name: database
    image: "neo4j:latest"
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7687:7687
      - 7474:7474
  backend:
    container_name: backend
    env_file: ".env"
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:3000
    healthcheck:
      test: curl -X GET --fail http://0.0.0.0:8000/health -Is
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 5s
