services:
  database:
    container_name: database
    image: "neo4j:4.4.14"
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7687:7687
      - 7474:7474
  backend:
    container_name: backend
    depends_on:
      - database
    volumes:
      - ./logs/:/logs/:rw
    environment:
      - ENV="DOCKER"
      - DB_PASS="test"
      - DB_ADDRESS="database"
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:81:3000
    healthcheck:
      test: curl -X GET --fail https://0.0.0.0:3000/health -Is --insecure
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 5s
  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:80:80

