services:
  database:
    container_name: database
    image: "neo4j:latest"
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7687:7687
      - 7474:7474
  backend:
    container_name: backend
    depends_on:
      - database
    volumes:
      - ./logs/:/logs/:rw
    environment:
      - DOCKER=true
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:80:7878
      - 0.0.0.0:443:3000
    healthcheck:
      test: curl -X GET --fail http://0.0.0.0:3000/health -Is --insecure
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 5s
